### PR TITLE
Multiple authors + various 

### PR DESCRIPTION
**Pull request by harpunius**
A few edits here (see the individual commits).

For redundancy:

1) Strips printing output in adamatch obejcts.
2) Simplifies the YEAR pattern \d\d\d\d to \d{4}. Could be something like [12]\d{3} instead.
3) Uses the YEAR pattern in other patterns
4) Fixes and-in-brackets (as you've started on)
5) Implements ampersand-in-text
6) Removes refdatedot check as it seems incorrect (requires period after date reference)
7) Uses for-each rather than for-loops (much simpler and removes ten matchList[i] lookups)

I tried to implement lookbehind rather than the tedious patterns, that match everything in their wake, but doing so I lost the context and was unable to provide useful suggestions (e.g. looking for & rather than capturing [\w\s]+\s&\s+[\w\s]+ you could just look for (?<=&).

### CODE REVIEW

**Comment by harpunius** [comment]
The conflict seem to be caused by me rearranging a line of code.

**Comment by harpunius** [comment]
Fixes #6

**Comment by keeferrourke** [comment]
Is this ready to be merged?

**Comment by keeferrourke** [comment]
Some interesting patterns to implement are mentioned in this blog post: http://blog.apastyle.org/apastyle/2011/02/changes-parentheses-bring.html

Namely, the use of Latin abbreviations within parentheses.

**Pull request merged**
